"""cache entry TTL

Revision ID: a1b2c3d4e5f6
Revises: b5cdd8e6e40a
Create Date: 2026-01-14

Written by hand rather than autogenerated because the batch call is required:
SQLite cannot drop or alter a column in place, so the table has to be rebuilt.
Autogenerate emits a plain ALTER that works on Postgres and fails on the SQLite
path that most people actually run in development.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "b5cdd8e6e40a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("cache_entries") as batch:
        batch.add_column(sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True))
        batch.create_index("ix_cache_entries_expiry", ["expires_at"])


def downgrade() -> None:
    with op.batch_alter_table("cache_entries") as batch:
        batch.drop_index("ix_cache_entries_expiry")
        batch.drop_column("expires_at")
