"""initial schema

Revision ID: b5cdd8e6e40a
Revises:
Create Date: 2026-10-08 16:18:07.318761

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b5cdd8e6e40a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache_entries",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "miss",
                "exact",
                "prefix",
                "semantic",
                name="cachetier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_access_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cache_entries")),
    )
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.create_index("ix_cache_entries_lru", ["tier", "last_access_at"], unique=False)
        batch_op.create_index("uq_cache_entries_tier_key", ["tier", "key_hash"], unique=True)

    op.create_table(
        "eval_results",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("suite", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_results")),
    )
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_eval_results_suite"), ["suite"], unique=False)

    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("dag_name", sa.String(length=128), nullable=False),
        sa.Column("partition", sa.String(length=64), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                "skipped",
                name="runstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_dag_name"), ["dag_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)
        batch_op.create_index(
            "uq_runs_dag_partition", ["dag_name", "partition", "input_hash"], unique=True
        )

    op.create_table(
        "spans",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.String(length=26), nullable=True),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spans")),
    )
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.create_index("ix_spans_trace_created", ["trace_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_spans_trace_id"), ["trace_id"], unique=False)

    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("name", name=op.f("uq_tenants_name")),
    )
    op.create_table(
        "budgets",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("tenant_id", sa.String(length=26), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("limit_micros", sa.BigInteger(), nullable=False),
        sa.Column("spent_micros", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_budgets_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budgets")),
    )
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_budgets_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index("uq_budgets_tenant_period", ["tenant_id", "period"], unique=True)

    op.create_table(
        "inference_requests",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("tenant_id", sa.String(length=26), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                "preempted",
                name="requeststatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "cache_tier",
            sa.Enum(
                "miss",
                "exact",
                "prefix",
                "semantic",
                name="cachetier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("ttft_ms", sa.Float(), nullable=True),
        sa.Column("tpot_ms", sa.Float(), nullable=True),
        sa.Column("queue_wait_ms", sa.Float(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_inference_requests_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inference_requests")),
    )
    with op.batch_alter_table("inference_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_inference_requests_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_inference_requests_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inference_requests_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                "cached",
                name="nodestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_nodes_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nodes")),
    )
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_nodes_run_id"), ["run_id"], unique=False)
        batch_op.create_index("uq_nodes_run_name", ["run_id", "name"], unique=True)

    op.create_table(
        "run_events",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("run_id", sa.String(length=26), nullable=False),
        sa.Column("node_name", sa.String(length=128), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
    )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_events_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_events_run_id"))

    op.drop_table("run_events")
    with op.batch_alter_table("nodes", schema=None) as batch_op:
        batch_op.drop_index("uq_nodes_run_name")
        batch_op.drop_index(batch_op.f("ix_nodes_run_id"))

    op.drop_table("nodes")
    with op.batch_alter_table("inference_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inference_requests_tenant_id"))
        batch_op.drop_index("ix_inference_requests_tenant_created")
        batch_op.drop_index(batch_op.f("ix_inference_requests_status"))

    op.drop_table("inference_requests")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_index("uq_budgets_tenant_period")
        batch_op.drop_index(batch_op.f("ix_budgets_tenant_id"))

    op.drop_table("budgets")
    op.drop_table("tenants")
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spans_trace_id"))
        batch_op.drop_index("ix_spans_trace_created")

    op.drop_table("spans")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index("uq_runs_dag_partition")
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_dag_name"))

    op.drop_table("runs")
    with op.batch_alter_table("eval_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_eval_results_suite"))

    op.drop_table("eval_results")
    with op.batch_alter_table("cache_entries", schema=None) as batch_op:
        batch_op.drop_index("uq_cache_entries_tier_key")
        batch_op.drop_index("ix_cache_entries_lru")

    op.drop_table("cache_entries")
    # ### end Alembic commands ###
